insert into Phones values ( 1, false, 'Samsung Galaxy S9', 'Guiseppe', '2024-04-28 14:30:00' );
insert into Phones values ( 2, false, '2x Samsung Galaxy S8', 'Viacheslav', '2024-04-29 10:00:00' );
insert into Phones values ( 3, false, 'Motorola Nexus 6', 'Max', '2024-04-26 15:45:00' );
insert into Phones values ( 4, true, 'Oneplus 9', NULL, NULL );
insert into Phones values ( 5, true, 'Apple iPhone 13', NULL, NULL );
insert into Phones values ( 6, true, 'Apple iPhone 12', NULL, NULL );
insert into Phones values ( 7, true, 'Apple iPhone 11', NULL, NULL );
insert into Phones values ( 8, true, 'iPhone X', NULL, NULL );
insert into Phones values ( 9, true, 'Nokia 3310', NULL, NULL );
insert into Phones values ( 10, true, 'Google Pixel 8', NULL, NULL );
